### ISSUE TITLE
Problem: rust is failing to build

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#132]

**Comment by clacke** [comment]
Could we simply pin to the latest nightly that worked?

**Comment by clacke** [comment]
Also related to #88.

**Comment by sjmackenzie** [comment]
Yeah, that's a neat idea actually. Do you know how to pin the mozilla-rust expression?

**Comment by clacke** [comment]
Not yet!

**Comment by clacke** [comment]
There we go.

```
# For a specific date:
#   rustChannelOf { date = "2017-06-06"; channel = "beta"; }.rust
```

https://github.com/mozilla/nixpkgs-mozilla/blob/327eccf80d64ac26244aff22d0d2f4060580568a/rust-overlay.nix#L291

PR incoming.
