### ISSUE TITLE
Problem: fbp scheduler is in nix land

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#150]
I can't put my finger on it entirely but I'll try:

The current architecture of the fbp scheduler is in fbp. Which means it'll be managed by nix. This poses a problem as the scheduler should be architected in normal racket code that is part of hyperflow. The reason is: hyperflow will execute nix, and it's much easier to have the scheduler aware of nix to get that dynamism. 

See, if we want hyperflow to load up a new component hierarchy then a new scheduler will be dependent on that hierarchy. We want to cut that dependency. So the hyperflow fbp scheduler will call nix for a new hierarchy of agents and unload the current graph if need be.

Also it's probably better to structure the scheduler as normal racket code so that it can easily be included into hyperflow.

In response to https://github.com/fractalide/fractalide/pull/149

**Comment by dmichiels** [comment]
So, the role of nix is to manage the agents installation, but no more the FVM (at least, no more tight together)?
We want to call nix from the FVM (which is part of hyperflow), to get the agent installation.

Is that possible to have a nix-hierarchy with all the agent (like for the moment in rust), and then call "nix-env -i agent-type ". It will install it (with edges,  build_dependency, ...) if necessary, and then return the correct path. And the FVM will load this path. 

Is that a correct way? 
A potential problem will be the loading time, because nix is not so quick...

**Comment by sjmackenzie** [comment]
correct nix manages the installation of the agents and just provides a path to the scheduler to run. 

I imagine there will be a separate racket module which will FFI into nix 2.0 and provide this path information to the scheduler. Hyperflow will then work with the scheduler to execute the graph. As per the mockups. I'd imagine a scheduler per (graph and run mode) tab on hyperflow.

We will work to the point where nix manages a hierarchy of edges and build_deps for ever racket agent in a hierarchy of agents. which will get loaded by the FVM (as you said).

Yes the load time will be slow for nix, but that's the cost of a reproducible system. We can reduce this by setting up a Hydra continuous integration system though and maybe FFI will help speed things up a bit.

But yeah, if the current FVM (in fbp style) is composable with hyperflow then we don't need to change the structure of the code to make it idiomatic racket. Just that the scheduler will *not* be managed by nix it'll be `required` directly into hyperflow.

**Comment by sjmackenzie** [comment]
We also need to think how to pass a racket gtk++ canvas object into the FVM and each agent in the hierarchy will receive this canvas object so that the agents can do GUI stuff.

For graphs that are in development, hyperflow will create a local development directory in `~/.racket/Hyperflow/fractal/*` for you to do your mutations. Then when the developer chooses to commit the code and upload it to github then publish the hierarchy by connecting it to the `fractalide/fractals/default.nix` they may do so when they wish.

**Comment by sjmackenzie** [comment]
So hyperflow should be able to run the scheduler but also if you have a GUIless fbp app you can run it with `fractalide/pkgs/hyperflow/flonly`. So the scheduler should be designed such that it can satisfy both use cases. The main difference between headless mode and hyperflow mode is passing in the canvas gtk++ object.

**Comment by sjmackenzie** [comment]
In Rust's case the fbp scheduler *is* managed by nix. Because nix will build out an FVM-as-a-shared-object then symlink the binary in the directory of the racket agent that will FFI into that FVM-as-a-shared-object binary.
