### ISSUE TITLE
Problem: GUI construction is not deterministic

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#161]
### Step to reproduce 
* `cd root/of/fractalide`
* `racket main.rkt test/main`
* close it 
* repeat running `racket main.rkt test/main` and closing 

### Expected behaviour
* textbox on the bottom always renders

### Actual behaviour
* textbox at bottom doesn't render 1  in ~10 runs

**Comment by dmichiels** [comment]
I didn't achieve to reproduce on my computer, but I will try to understand how it is possible!

**Comment by sjmackenzie** [comment]
By following the `steps to reproduce` I have achieved non-determinism in the gui.
![nondeterministic-gui-1](https://user-images.githubusercontent.com/158321/40176330-9dd0d27c-5a0d-11e8-8cc1-b7eee7b714ec.png)
note the position of the slider in the two examples
![nondeterministic-gui-2](https://user-images.githubusercontent.com/158321/40176337-a20724f4-5a0d-11e8-9c0e-a3d116903999.png)
