### ISSUE TITLE
Problem: semantics of graph language `iip` feels a bit alien to people.

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#175]
Solution: 

* Rename Initial Information Packet (`iip`) to Initial Message (`imsg`)

* `imsg` has the advantage of being 4 characters like `node` & `edge`, so the text lines up nicely.
Secondly we're sending messages, and `msg` is more intuitive for people.

**Comment by dmichiels** [comment]
I ask my-self the necessity of the `initial` part. I think I prefer `msg` over `imsg`. When we declare the graph, we just say : they are messages, like we say : they are nodes (we don't put `inode` for `initial node`...).

We just loose the 4 characters constant, but for me it will less burden brain's user (there is no semantic difference between a `msg` and a `imsg`).

**Comment by sjmackenzie** [comment]
Yeah glad you agree with the `iip` -> `?msg` idea.

How about this: `iip` -> `mesg` ?

That'll work nicely

**Comment by dmichiels** [comment]
`mesg` seems a little strange at first for my eye, but it seems to be the a good choice. Let go for `mesg`!

**Comment by sjmackenzie** [comment]
yeah it's a common convention, at least with `dmesg`! :-) I think our eyes will grow accustomed to it soon enough.
