### ISSUE TITLE
Problem: preliminary stages of a graph language compatible with nix not in place

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#176]
Solution: The current process of defining graphs seems succinct and powerful enough to describe our needs. Though there is one change needed to make initial preparation for nix integration (much later) complete. At least this allows us to get used to the new semantics of the language and when we finally integrate `nix` all the graphs will work with minimal changes.

Actual behaviour to setup a node:
```
(node "frame" "gui/frame")
```
Expected behaviour to setup a node:
```
(node "frame" "${gui.frame}")
```

The name for a node should be the same as the nix attribute name surrounded by `${...}`. The racket code receiving this string will conditionally execute depending on the the presence of a `${` in the beginning of the string.

1. when compiling as racket only and no nix integration, the receiving code will see the string "${gui.frame}". Racket should then lookup the path to the gui/frame file. At a later stage we can push all the `fractal` into the `~/.racket/fractal` directory. So racket will see `${gui.frame}` and find the file `~/.racket/fractal/gui/frame.rkt`. For the moment looking up in `agents` directory is sufficient.
2. when we introduce nix at a later stage, nix will precompile the racket "graph" file and transform the names `${...}` into `"/nix/store/..."`. So if the receiving code of that string doesn't see a `"${"` then it knows to look up that absolute path "/nix/store/..." for the file.

**Comment by dmichiels** [comment]
Yes, it seems a good step for later.

# loading the graph

For me, the graph loader must do : 
- check if the path exist (this case is when nix "precompile" the graph)
- If no, send the type to the agent "get-path"
  - This agent will first look for 'nix-env -i ...', to see if the node is already installed (but the graph is not yet compiled)
  - Then look for ~/.racket/... (The node is under dev, or unpublished)

So we have a very generic way to access our agent, with and without nix.

# Proposition for the syntax

I think the syntax will be clearer if it is 

```
(node "frame" ${gui.frame})
```
and not 
```
(node "frame" "${gui.frame}")
```
The type is not a string in my proposition. I did some test with macro, it is possible.

# Limitation

I just think that disallow user to use `.` in agent name, but that is not a problem.

**Comment by sjmackenzie** [comment]
Great: `"${name}"` -> `${name}`, it actually adds more colour to the code, instead of looking at a sea of 
strings. So it's easier on the eyes this way. 

Regarding the `.`: we need to remember that `${name}` is actually nix code,  the `.` is the way to access attributes. Meaning that we cannot deviate from it. So typically `fractal` will export a flat set of attributes. When accessing nodes we'll call `${<fractal>.<node>}`. So for the mean time the structure in the `agents` directory should be `agents/<fractal>/<nodes>` and we'll just refer to it as `${fractal.node}` or just `${node}`.

For example: https://github.com/fractalide/fractal_workbench/blob/master/nodes/rs/workbench/default.nix#L11

**Comment by sjmackenzie** [comment]
Ah yes "I just think that disallow user to use . in agent name, but that is not a problem." sorry, I understand your meaning now. You're right, using `.` would cause problems.

**Comment by sjmackenzie** [comment]
If you can get `${name}` to work then maybe we can get it such that there are no strings.

I.e. 
``` racket
(edge but-add out _ hp place 10)
```
Then when we make it a new racket language (cause it'll need to other background jobs like call nix etc) we can do the DrRacket thing of drawing arrows in code. This allows you to quickly and easily see where that port is connecting to.

http://lists.racket-lang.org/users/archive/attachments/20150103/23cadb91/attachment-0002.png

**Comment by dmichiels** [comment]
I'm thinking also of another issue for compatibility while using or not `nix` : import of edges. 
For the moment, there is one `edge`import in `test/dynamic.rkt`.

I'm not sure, but perhaps we can use a similar way as `node`?

Like in the begining of the file : 
```
edge(${fvm.dynamic-add})
edge(${math.boolean})
```

Again, if it is a full path (compiled by nix), it will require the path. If not, it will look in `~/.racket/fractal/.../edges/...`.

I'm not sure yet it is easy to implement with macro, but we must found a solution for this.

**Comment by sjmackenzie** [comment]
Yeah I've been mulling over that too.

It would look something like 
`(define-edge dynamic-add ${fvm.dynamic-add})`

Then later we could the `edge` macro would need to accept another parameter

`(edge dynamic-add dynamic out _ vp place 99)`

if the you use `edge` without the `edge contract` then it would be.

`(edge _ dynamic out _ vp place 99)`

But now we already have many parameters for a function!

Also there's something else I've been thinking about, but I'm not sure on. Maybe we should only use edges at `fractal` level? This then becomes the public "API" so to say. But there might be times when people want a node nested deep within a fractal. This approach keeps it light without having to maintain n+1 edge contracts.

**Comment by dmichiels** [comment]
I will look for the 
```
 (define-edge dynamic-add ${fvm.dynamic-add})
```
syntax.

However, for the "typed edge", I think this information must be in the agent declaration : 
```
#:input '( (in : dynamic-add) (get-graph : string)))
#:output '( (out : any) )
```
This will allow to connect agent that get the same type, and no definition on graph building.

**Comment by sjmackenzie** [comment]
Yes, the only exposure of `edge types` at the graph level is via the `mesg`.

Actually we probably want to expose (at agent level)
`(require-os-deps nixpkgs-attribute1 nixpkgs-attribute2)`
`(require-edge edge1 edge2)`
`(require-module racket-mod1 racket-mod2)`

At graph level we can expose:
`(require-edge edge1 edge2)`
`(require-node node1 node2)`

For compiling via hyperflow-calling-nix then a `default.nix` is created with these deps

When compiling in pure racket mode, things get more difficult.

Maybe, we can point the those deps at the relative fractal in the `~/.racket/fractal` directory and regarding the `racket-modules`, luckily claes is working on racket2nix such that we can obtain the deps without nix. As for nixpkgs-deps, well we might need to run `nix-shell -p ...` in the background. This is a bit of an known-unknown issue.

**Comment by sjmackenzie** [comment]
Yes you're absolutely right about 
```
#:input '( (in : dynamic-add) (get-graph : string)))
#:output '( (out : any) )
```
I just worry, we're probably going to need to do this:
```
#:input '( (in : ${fvm.dynamic-add}) (get-graph :${string})))
#:output '( (out : ${any}) )
```
Then allow a "pass through" for racket datatypes but if there's a `.` or something that isn't a racket datatype we're going to need to use the same (nix/racket) lookup mechanism as we will have for nodes in a graph.

**Comment by dmichiels** [comment]
1) `require-os-deps`
For the 
```
(require-os-deps nixpkgs-attribute1 nixpkgs-attribute2)
```
must that not be in  `default.nix`, as for the Rust version? I don't believe we must manage that at the racket level, it is not the goal of a module. If the users doesn't use nix, they must install deps manually?

2) For the edge type
I beleive that `dynamic-add` will be imported first with `(require-edge dynamic-add ${bla})`. So no need in the agent definition.

**Comment by sjmackenzie** [comment]
1. Yes you're probably right, end users will be calling dapps via hyperflow-calling-nix, developers will need to know how to add nixpkg-deps into their environment. So we can just `require-os-deps` to *just* help generate the `default.nix` but it won't be used to setup the environment. I'm afraid yet-again nix will be a hard dependency for the end users. It's our package manager and this sort of application must have a package manager. The racket mode only is to make it convenient for programmers to develop fast and easily.

2. Ah okay I see! Then we can access it throughout the code. Yes that makes more sense!

**Comment by sjmackenzie** [comment]
So we'll be getting fractalide  (nix) to run on macos + linux + windows 10 (https://twitter.com/zimbatm/status/911992348858601474) there's a trick to get the gui to work but at least we can see the end in sight.

**Comment by clacke** [comment]
Debatable whether WSL counts as Windows. Ideally we should have Nix working in cygwin and/or msys2, but that's a big question mark at the moment, we'd have to look at what the status is on Nix on Windows.

**Comment by sjmackenzie** [comment]
Hence the "windows" download link is greyed out https://github.com/fractalide/fractalide-website-styx/issues/145 :-)

**Comment by dmichiels** [comment]
I believe that with #196, "all" the problems are solved? So we can close this issue? (we will have to wait for windows, but that is not related to this repo)
