### ISSUE TITLE
Potential Problem: if racket gui fails us, and doesn't look good on other platforms

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#185]
Solution: create a new gui language that wraps this: https://github.com/andlabs/libui

Please keep track of alternatives in this issue. As the user interface is a make or break feature of the project.

**Comment by dmichiels** [comment]
Also, it is interesting to not that `libui` can perhaps work for a full `rust` solution. So when tracking, see if it is a `racket`, `rust` or `racket + rust`  solution.

**Comment by sjmackenzie** [comment]
Yes indeed it did cross my mind :-) (https://github.com/LeoTindall/libui-rs) It would be an ideal solution if that was so, but alas there are many unknowns down that direction and I'd rather go with something that seems most likely to work, i.e. racket gui. Later we can look at building this layer up (which'll require a new racket gui + a lot of debugging and development for the rust layer.)

**Comment by dmichiels** [comment]
Yes for sure, it is a long-term reflection.

**Comment by clacke** [comment]
Andlabs, eh? I know them from the Fediverse. ;-)

**Comment by sjmackenzie** [comment]
`gtk3` seems nice enough, closed by https://github.com/NixOS/nixpkgs/pull/41557
