### ISSUE TITLE
Problem: a card stack (from hypercard) is required for building graphical dapps

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#193]
Solution: implement a card stack in fbp allowing cardano-wallet to use it for the gui

**Comment by dmichiels** [comment]
You want something to switch between different card? Like 'place-holder' in the Oz version? It is to be sure to understand the goal of this issue.

**Comment by sjmackenzie** [comment]
Take a look at page 48 of your thesis: https://github.com/fractalide/fractalide-oz/blob/master/docs/fractalideCOP.pdf

**Comment by dmichiels** [comment]
I believe that #194 will be a good solution for this issue. It is not the "stack" from hyper-card, but a versatile widget "place-holder" that will feed the need of this. 
The "stack" is a little less in the mind of the current state of the UI building, but it can be easily created now.
