### ISSUE TITLE
Problem: define-agent: We always want to define the 'agt symbol

### ISSUE THREAD

**Issue by clacke** [fractalide/fractalide#217]
We are repeating ourselves with `(define agt (define-agent`, as the agent loader is always looking for the `agt` symbol.

Solution: `define-agent` or some other form includes the `(define agt ` bit.

**Comment by dmichiels** [comment]
I comment here, but it concerns #216 also.

You are right we can clean a little the agent declaration, but I'm not sure to go as far as you describe in #216.

I achieve this result to defining an agent (it is a complete file): 
```
#lang racket

(require fractalide/modules/rkt/rkt-fbp/agent)

(define-agent
  #:input '("a" "b")
  #:output '("out")
  ((input output input-array output-array)
   (define a (recv (input "a")))
   (define b (recv (input "b")))
   (send (output "out") (nand a b))))
```

I don't think it is possible to get rid of the lambda arguments declaration... Do you have an example were there is argument in a "finish-close like"?
