### ISSUE TITLE
Problem: scheduler: repeating ourselves when calling it

### ISSUE THREAD

**Issue by clacke** [fractalide/fractalide#218]
```
(define sched (make-scheduler #f))
(sched (msg-add-agent "sched" "agents/fvm/scheduler.rkt"))
(sched (msg-add-agent "load-graph" "agents/fvm/load-graph.rkt"))
(sched (msg-add-agent "get-graph" "agents/fvm/get-graph.rkt"))
[ . . . ]
```

`sched` here could take a whole list of messages instead.  Also I wrapped this up in a setup function in the package `fvm` in cardano-wallet and it properly belongs in fractalide.

Is it possible to use the graph language for this? Or is this a bootstrap situation where the graph language cannot work because this stuff isn't in place yet?

Also:

    (sched (msg-mesg "sched" "acc" (make-scheduler #f)))

I'm guessing it's important that this is a second scheduler, but I don't understand `fvm` enough yet to understand how the two schedulers work together.

Is it simply the case that `fvm` is a tool for setting up the graphs for fbp applications? And it just happens to be implemented as an fbp application too? (only without the benefit of using itself for setting itself up)

**Comment by dmichiels** [comment]
> sched here could take a whole list of messages instead.

Yes, that is true, I will change the scheduler method to accept a list

>  Also I wrapped this up in a setup function in the package fvm in cardano-wallet and it properly belongs in fractalide.

Exactly, for the moment, fbp-rkt is provided as "executable" and not as a library. We must add a function to allow other module to use it.

> Is it possible to use the graph language for this? Or is this a bootstrap situation where the graph language cannot work because this stuff isn't in place yet?

Your guess is correct, this is the program that can manage the graph...

> Is it simply the case that fvm is a tool for setting up the graphs for fbp applications? And it just happens to be implemented as an fbp application too? (only without the benefit of using itself for setting itself up)

True, the scheduler only manage 'agent', not subgraph. And all the subgraph stuff are implemented with the help of agents. So the first time, no way to use the graph... (even if now, the fvm is also implemented as graph here : agents/fvm.rkt).
