### ISSUE TITLE
Problem: fvm: No obvious way to send IIPs to loaded graph

### ISSUE THREAD

**Issue by clacke** [fractalide/fractalide#246]
The current test graph is triggered by someone clicking in the UI, but I couldn't find a way for a headless automated test to send messages to nodes inside the graph, or to the virtual input of the graph. When looking at the `scheduler-agents` of the application scheduler, it's the empty list.

For automated testing, I currently set up the scheduler explicitly, rather than loading a graph via fvm.

**Comment by sjmackenzie** [comment]
you can kickstart a graph by sending a `(mesg "node" "port" #t)` try that out. Within the node you won't actually care about receiving the data and doing something with it. If you want the node to run once, then you'll take that packet of the bounded buffer, if you want the node to run continuously then leave that packet on the queue.

**Comment by clacke** [comment]
There is no node after the graph has been set up, only within the graph definition.

**Comment by sjmackenzie** [comment]
@dmichiels ping

**Comment by clacke** [comment]
I retract the retraction. Even with an `(edge-in)` the node is not present in the child scheduler after fvm processed the graph.

**Comment by clacke** [comment]
Oh wait, actually in my examples (all derived from `test/main`) I'm not adding the graph. I'm adding a graph that refers to the graph -- and that referring graph doesn't have any edges in or out.

**Comment by clacke** [comment]
The solution is probably to send the messages within the `(make-graph)` and then add it with `dynamic-add`, using the `"dynamic-out"` edge out and adding the `tap` (what the test verification reads) as the `sender`.

**Comment by dmichiels** [comment]
If I understand well, you are adding a graph with `(send-dynamic-add graph input output)`.
If the graph is : 
```
(make-graph
        (node "vp" "${gui.vertical-panel}"))
```
Normally, you can send message inside the graph by doing a new graph, send again by send-dynamic-add : 
```
(send-dynamic-add (make-graph
    (mesg "vp" "in" ...)) input output)
```
All the node must be accessible, but if `vp` is a sub-graph, you need to use `edge-in`.
Is that helping you?

**Comment by clacke** [comment]
I didn't realize that a graph with just a `(mesg)` would be a valid thing to add too. But of course! Thanks, will try that and report my success. :-)

**Comment by dmichiels** [comment]
Yes, dynamic-add and dynamic-remove is "imperative" style. So you can interact with the "dynamic running" graph.

**Comment by sjmackenzie** [comment]
@clacke did you achieve success? May we close this?

**Comment by clacke** [comment]
Didn't try it yet, but closing as this looks like a plausible method.
