### ISSUE TITLE
Problem: current user experience for graph mode doesn't work too well for laptops with touchpads

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#282]
Potential solution:

It might be good to emulate this approach: https://ncase.me/crowds/
(If you go to sandbox mode you can see how nodes are added and deleted)

Food for thought

**Comment by dmichiels** [comment]
So the solution proposed is "tool menu", as there is in `Gimp` and in `crowds`? It will perhaps burden a little the UI?

Other proposition : 
As there will be the name on the node, we can imagine that clicking on the name is for moving, and clicking on the circle (not on the name) will create a edge, like in `crowds` (so you have to maintain the click, if you release on an other node, the edge is created.

**Comment by sjmackenzie** [comment]
I think once we have have the basics (add, remove, etc) we'll work over the UX with @dapyh17d4. It's very easy for us to cock this up for the end user. So for the moment I suppose just go with whatever your intuition is.
