### ISSUE TITLE
Problem: travis times out on the `plot-compat` racket dependency

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#283]
```
...
trying https://download.racket-lang.org/releases/6.12/pkgs/plot-compat.zip
curl: (7) Failed to connect to download.racket-lang.org port 443: Connection timed out
...
```
https://travis-ci.org/fractalide/fractalide/jobs/414599229

**Comment by clacke** [comment]
Yes, once we have pulled down a zip on Hydra, Nix will pick the zip from there rather than from `racket-lang`:

> `copying path '/nix/store/zfl5grxh817nlci4ffa3f1gf4hm3y7l2-net-cookies-doc.zip' from 'https://hydra.fractalide.com'...`

(as seen in #286 Travis runs)
