### ISSUE TITLE
Problem: graph load fails

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#306]
### Steps to reproduce:
* ensure you're on at least https://github.com/fractalide/fractalide/pull/305 (2a79763)
* `$ racket fvm.rkt agents/hyperflow/run.rkt`
* menu graph -> open
* select `agents/test/load.rkt`. 

### expected behaviour
* the nodes appear in graph mode

### actual behaviour
```
$ racket fvm.rkt agents/hyperflow/run.rkt
Gtk-Message: 16:49:55.991: GtkDialog mapped without a transient parent. This is discouraged.
Agent main-graph-load fails with : 
#(struct:exn:fail:read string::1: string->jsexpr: bad input #<continuation-mark-set> (#(struct:srcloc string #f #f 1 #f)))
```

**Comment by dmichiels** [comment]
Perhaps it is because it use the program "graphviz" to found the layout. Is `dot` command install on your computer?

**Comment by sjmackenzie** [comment]
AH! I see!

**Comment by sjmackenzie** [comment]
It works well! nice!
