### ISSUE TITLE
Problem: Unable to get hyperflow to load a graph

### ISSUE THREAD

**Issue by clacke** [fractalide/fractalide#318]
How are you guys doing it?

1. `$ nix-shell -p $(nix-build -A pkgs.fractalide.env) --run hyperflow`
1. Window opens up
1. Click Graph->Open, open e.g. `test/main`.
1. Receive this: 

```
[ GTK nonsense filtered ]
Agent main-graph-in-agent fails with : 
#(struct:exn:fail:contract cadr: contract violation
  expected: (cons/c any/c pair?)
  given: '("/home/clacke/git/fractalide/no-more-fun/modules/rkt/rkt-fbp/agents/test/main.rkt") #<continuation-mark-set>)
```

**Comment by sjmackenzie** [comment]
Not `test/main` but `agents/hyperflow/run.rkt` also starting hyperflow is a bit different and inconsequential. `racket fvm.rkt agents/hyperflow/run.rkt`

**Comment by clacke** [comment]
`racket fvm.rkt agents/hyperflow/run.rkt` and `hyperflow` are supposed to be equivalent, and I'm pretty sure they are. Anyway, nothing is working and it's a mystery.

And last night we saw that the `string->jsexpr` issue when loading a graph happens on your machine too, when we tried to wrap `${hyperflow.graph}` in a slideshow presentation.

**Comment by sjmackenzie** [comment]
I just ran it this way:
```
$ nix-build -A pkgs.fractalide
$ ./result/bin/hyperflow 
Gtk-Message: 16:37:59.720: GtkDialog mapped without a transient parent. This is discouraged.
in agent main-graph-get-graph:
default-load-handler: cannot open module file
  module path: #<path:/home/stewart/dev/fractalide/fractalide/agents/cardano-wallet.rkt>
  path: /home/stewart/dev/fractalide/fractalide/agents/cardano-wallet.rkt
  system error: No such file or directory; errno=2
  context...:
   standard-module-name-resolver
   ...t/private/kw.rkt:446:14
   /nix/store/1ga5nfxljdnp1w7a9jbn06yvsfva4jqa-racket-minimal-6.12-fractalide-env/share/racket/pkgs/fractalide/modules/rkt/rkt-fbp/scheduler.rkt:223:18
```
I then tried opening the `cardano-wallet.rkt` - the above is the error.

I then ran it like this:
```
$ racket fvm.rkt agents/hyperflow/run.rkt
```
then opened the `cardano-wallet.rkt` graph to great success!

**Comment by sjmackenzie** [comment]
even after applying #321 then opening a `cardano-wallet.rkt` file I get this error:

```
$  nix-shell -p $(nix-build -A pkgs.fractalide.env) --run hyperflow 
Gtk-Message: 16:48:23.484: GtkDialog mapped without a transient parent. This is discouraged.
in agent main-graph-get-graph:
default-load-handler: cannot open module file
  module path: #<path:/home/stewart/dev/fractalide/fractalide/agents/cardano-wallet.rkt>
  path: /home/stewart/dev/fractalide/fractalide/agents/cardano-wallet.rkt
  system error: No such file or directory; errno=2
  context...:
   standard-module-name-resolver
   ...t/private/kw.rkt:446:14
   /nix/store/ha20k67hcf27pk183d763vsd07a7qbwi-racket-minimal-6.12-fractalide-env/share/racket/pkgs/fractalide/modules/rkt/rkt-fbp/scheduler.rkt:223:18

```

**Comment by clacke** [comment]
@sjmackenzie What happens if you run:

```
modules/rkt/rkt-fbp$ nix-build ../../.. -A pkgs.fractalide
modules/rkt/rkt-fbp$ ./result/bin/hyperflow
```

and then try to open `cardano-wallet.rkt`?

**Comment by sjmackenzie** [comment]
that works!

**Comment by clacke** [comment]
Yeah, so the problem here is that the loader in hyperflow is like the loader in fvm.rkt used to be, and looks in the current directory instead of in the rkt-fbp directory.

**Comment by clacke** [comment]
That still doesn't explain why it doesn't work on my machines. :-(

**Comment by clacke** [comment]
Oh! That jsexpr error, it's probably again because graphviz is missing. :-)

I'll add a check for it.

**Comment by sjmackenzie** [comment]
Ah right, that's probably it.
