### ISSUE TITLE
all cardano crates are not available

### ISSUE THREAD

**Issue by dmichiels** [fractalide/fractalide#334]
While implementing the Cardano nodes, I need the crates : `storage`, `storage_units`, `exe_common`, `protocol`, available here : https://github.com/input-output-hk/rust-cardano/tree/master. For the moment, I only achieve to get the `cardano_0_1_0`, and not any `cardano_storage_0_...`

I still don't understand how the magic of Nix, so I didn't achieve to add them myself.

**Comment by sjmackenzie** [comment]
Denis, i'll do it for you tonight!

**Comment by sjmackenzie** [comment]
@dmichiels take a look (and merge when ready) https://github.com/fractalide/fractalide/pull/335

**Comment by sjmackenzie** [comment]
for future reference:

add what you need [here](https://github.com/fractalide/fractalide/blob/master/modules/rs/crates/Cargo.toml.nix)
ensure the [attribute name](https://github.com/fractalide/fractalide/blob/master/modules/rs/crates/Cargo.toml.nix#L19) is the same as the [package name](https://github.com/fractalide/fractalide/blob/master/modules/rs/crates/Cargo.toml.nix) of the crate

Then run [`$ ./update.sh`](https://github.com/fractalide/fractalide/blob/master/modules/rs/crates/update.sh)
