### ISSUE TITLE
Problem: modules/rs/crates/update.sh: Latest carnix does not work

### ISSUE THREAD

**Issue by clacke** [fractalide/fractalide#347]
Steps to reproduce:

1) Fix that `update.sh` calls `carnix nix`. It's now called `carnix generate-nix`.
2) The generated `Cargo.nix` requires some new parameters. Forward those from `buffet.pkgs`.
3) `(cd modules/rs/crates && ./update.sh)`
4) `./release.sh`

```
error: while evaluating the attribute 'mods.rs.cardano_0_1_0' at /home/clacke/git/fractalide/fractalide/modules/default.nix:4:3:
attribute 'cardano_0_1_0' missing, at /home/clacke/git/fractalide/fractalide/release.nix:8:15
```

**Comment by sjmackenzie** [comment]
Huh? I'll take a look at this when I wake up.

**Comment by clacke** [comment]
Reproduction in https://github.com/clacke/fractalide/tree/carnix-generate-nix

**Comment by clacke** [comment]
Cargo.nix now only exports:

```
rec {
  all_crates = crates.crates.all_crates."1.1.1" deps;
  __all = [ (all_crates {}) ];
  deps.aho_corasick."0.6.9" = {
  [ . . . ]
```

Can only get at the package declared in the `Cargo.toml`, from what I can see. The dependencies are hidden from sight.

**Comment by sjmackenzie** [comment]
I couldn't reproduce this the `generate-nix` argument was invalid.

**Comment by sjmackenzie** [comment]
it executed well actually

**Comment by sjmackenzie** [comment]
I'm currently on 
```
$ carnix --version
carnix 0.7.2
```
let me upgrade and try reproduce.

**Comment by sjmackenzie** [comment]
okay I've reproduced it...

**Comment by sjmackenzie** [comment]
if you change the release.nix to use this:
```
    cardano = (import ./. { inherit pkgs; }).mods.rs.deps.cardano."0.1.0";
    rustfbp = (import ./. {}).mods.rs.deps.rustfbp."0.3.34";
```
it works. (well still compiling, but it least the nix evaluated)

**Comment by clacke** [comment]
Oh! The structures are so convoluted, I thought the deps attributes were just full of sub-attributes that defined what versions of things the crates wanted.

Alright then, thanks for digging!

**Comment by sjmackenzie** [comment]
Significant changes to carnix generated code that needs to sweep throughout the rust-fbp code too. Actually these changes ale much better imho. More readable and separates out the crateIO.nix file which can be used in nixpkgs ala cananical cratesIO.nix. Not sure how it'll unravel but keen to see.

**Comment by clacke** [comment]
too bad the nixpkgs one is out of date. I wonder if there is a way to make carnix consider that and generate just enough to fill in the gap.

**Comment by sjmackenzie** [comment]
hehe, I think that's the end goal :-) let's see what happens! Though it shouldn't affect us too much we just pull in our cratesIO.nix and be done with it.
