### ISSUE TITLE
Problem: TravisCI future looks shaky

### ISSUE THREAD

**Issue by clacke** [fractalide/fractalide#362]
https://twitter.com/ReinH/status/1098663375985229825

> So apparently Travis CI is being strip-mined immediately after their acquisition by Idera. Sorry, I mean after "joining the Idera family"

https://www.reddit.com/r/devops/comments/at3oyq/it_looks_like_ibera_is_gutting_travis_ci_just_a/

>  have no idea, they just sent termination letters to lots of peeps, including senior engs (like the ones with the most institutional knowledge? What?!), support, COO, etc... so....IDK?

Solution: Taking a look at GitLab CI and other solutions to keep in handy if Travis starts deteriorating.

**Comment by clacke** [comment]
This doesn't necessarily mean leaving GitHub. Looks like GitLab CI already supports GitHub integration:

https://gitlab.com/gitlab-org/gitlab-ee/issues/3835

**Comment by clacke** [comment]
I tried https://builds.sr.ht/~clacke/job/32470 for racket2nix, and that was trivial to set up.

`.build.yml` https://builds.sr.ht/api/jobs/32470/manifest : 

```
image: nixos/latest
sources:
 - https://github.com/fractalide/racket2nix.git
tasks:
 - setup: |
     cd racket2nix
     sudo -i nix-channel --add https://nixos.org/channels/nixpkgs-unstable
     sudo -i nix-channel --update
     sudo -i $PWD/support/utils/setup-hydra.fractalide.com.sh
 - build: |
     cd racket2nix
     ./release.sh
```

If we want to use this, someone with `Owner` access to the repos will have to authenticate from https://dispatch.sr.ht/ and set up the web hooks.

**Comment by sjmackenzie** [comment]
Okay excellent i'll set this up today! Thanks!
