### ISSUE TITLE
Provide simple example setting up a python environment

### ISSUE THREAD

**Issue by shism2** [fractalide/fractalide#370]
It would be appreciated as the documentation is complicated

**Comment by sjmackenzie** [comment]
there is no python environment

**Comment by shism2** [comment]
Ok. So, it can't be used to create ephemeral dev environments for example?

**Comment by sjmackenzie** [comment]
Dude, I think you should go setup an ephemeral dev environment using nix shell. This project just makes use of nix. Please take a look an nixos.org

**Comment by shism2** [comment]
Ok thanks for the advice.

Thank You,
Julio

**Comment by sjmackenzie** [comment]
https://nixos.org/#asciinema-demo-cover
