### ISSUE TITLE
Problem: need a fast way to create nodes, edges and fractals

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide#84]
Solution:

Create a program called `fractalide` which accepts arguments
```
fractalide new edge <name>
fractalide new node <name>
fractalide new fractal <name>
fractalide 2nix idris
fractalide 2nix rust
fractalide 2nix racket
```
This tool makes it easy far people to spin up new components.

The `2nix` arguments call the relevant programs that generate the necessary nix dependencies in the modules directory.

The program should be structured as a library to be included in the hyperflow (a hypercard clone). This allows one to spin up nodes and edges from the gui as well as from the fractalide-cli application.

**Comment by clacke** [comment]
Bikeshed opinions: `fractalide create` and `fractalide generate-nix` or just `fractalide nix`.
